#title in header
title: "rthmr.de"

#main info
#owner
owner: "Tobias Reithmeier"
email: tobias@nerdwana.net
info: "Frontend developer with focus on TypeScript and Angular. Former full stack PHP developer. Certified project manager. Scrum savy."
#description
desc: ""

#menu
menu:
  √úber: /ueber
  Impressum: /impressum

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
github: https://github.com/ComicSans
twitter: https://twitter.com/rthmr

# Misc
nanobar: /js/nanobar.min.js
switch_light: ‚òÄÔ∏è
switch_dark: üåë

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io
